basePath: /
host: localhost:8080
info:
  contact: {}
  description: Example REST_API for demonstrating Swagger with Echo framework.
  title: Echo Swagger Example REST_API
  version: 1.0.0.
paths: {}
swagger: "2.0"
